services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: aulajpa
      MYSQL_USER: dev
      MYSQL_PASSWORD: 12345667
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
