file:
  upload-dir: src/main/resources/media

spring:
  application:
    name: "Spring-and-JavaErudio"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none


  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 250MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aulajpa
    username: dev
    password: 12345667


springdoc:
  api-docs:
    path: /api/v1/docs
    enabled: true

  swagger-ui:
    use-root-path: true
    path: /api/v1/docs

  paths-to-match: /api/**/v1/**

cors:
  originPatters: http://localhost:8080
